### ISSUE TITLE
いくつかのリソースの紹介

### ISSUE THREAD

**Issue by kaisugi** [taishi-i/awesome-japanese-nlp-resources#1]
こんにちは。
素晴らしいリポジトリで感動しました。（私の記事である『フリーで使える日本語の主な大規模言語モデルまとめ』もご紹介いただきありがとうございます！）

私が過去に GitHub でスターをつけたリソースのうち、まだこのリポジトリに載っていなさそうなものを僭越ながら書いてみます。

- [atilika/kuromoji](https://github.com/atilika/kuromoji) Kuromoji is a self-contained and very easy to use Japanese morphological analyzer designed for search
- [takuyaa/kuromoji.js](https://github.com/takuyaa/kuromoji.js) JavaScript implementation of Japanese morphological analyzer
- [daac-tools/vaporetto](https://github.com/daac-tools/vaporetto) 🛥 Vaporetto: Very Accelerated POintwise pREdicTion based TOkenizer
- [ku-nlp/bertknp](https://github.com/ku-nlp/bertknp) A Japanese dependency parser based on BERT
- [KoichiYasuoka/esupar](https://github.com/KoichiYasuoka/esupar) Tokenizer POS-Tagger and Dependency-parser with BERT/RoBERTa/DeBERTa models for Japanese and other languages
- [izuna385/jel](https://github.com/izuna385/jel) Japanese Entity Linker.
- [WorksApplications/chiVe](https://github.com/WorksApplications/chiVe) Japanese word embedding with Sudachi and NWJC
- [nttcslab/japanese-dialog-transformers](https://github.com/nttcslab/japanese-dialog-transformers) Code for evaluating Japanese pretrained models provided by NTT Ltd.
- [octanove/shiba](https://github.com/octanove/shiba) Pytorch implementation and pre-trained Japanese model for CANINE, the efficient character-level transformer.
- [reppy4620/Dialog](https://github.com/reppy4620/Dialog) A PyTorch Implementation of japanese chatbot using BERT and Transformer's decoder
- [retarfi/language-pretraining](https://github.com/retarfi/language-pretraining) BERT and ELECTRA models of PyTorch implementations for Japanese text.
- [ou-medinfo/medbertjp](https://github.com/ou-medinfo/medbertjp) Trials of pre-trained BERT models for the medical domain in Japanese.
- [sociocom/MedNER-J](https://github.com/sociocom/MedNER-J) Latest version of MedEX/J (Japanese disease name extractor)
- [stockmarkteam/ner-wikipedia-dataset](https://github.com/stockmarkteam/ner-wikipedia-dataset) Wikipediaを用いた日本語の固有表現抽出データセット
- [SkelterLabsInc/JaQuAD](https://github.com/SkelterLabsInc/JaQuAD) JaQuAD: Japanese Question Answering Dataset for Machine Reading Comprehension (2022, Skelter Labs)
- [tsuruoka-lab/BSD](https://github.com/tsuruoka-lab/BSD) The Business Scene Dialogue corpus
- [ikegami-yukino/dataset-list](https://github.com/ikegami-yukino/dataset-list) lists of text corpus and more (mainly Japanese)

このリポジトリの趣旨に合うものがあれば追加してみてください。

**Comment by taishi-i** [comment]
情報、ありがとうございます🙏
内容を更新しました！非常に助かります！

現在の方針としては、Python で動作するライブラリ、コーパス、辞書、事前学習モデルの情報を収集しています。

なので、kuromoji.js, vaporettoは、
Javascript で動作するライブラリ、Rust で動作するライブラリをまとめる際に追加致します。

もしよろしければ、Contributors に追加させていただきたいので、
README.md の Contributors に Twitter などのリンクを記載いただき、プルリクを送っていただけないでしょうか？

## Contributors

 * [HelloRusk](https://github.com/HelloRusk) - **Twitterなどのリンクを記載**
 
 よろしくお願いします！

**Comment by kaisugi** [comment]
> なので、kuromoji.js, vaporettoは、Javascript で動作するライブラリ、Rust で動作するライブラリをまとめる際に追加致します。

なるほど、そうだったのですね！

**Comment by kaisugi** [comment]
> もしよろしければ、Contributors に追加させていただきたいので、
README.md の Contributors に Twitter などのリンクを記載いただき、プルリクを送っていただけないでしょうか？

すみません、Twitterは一応あるのですが、全く動かしておらず...
代わりに自分のウェブサイトを

- [HelloRusk](https://github.com/HelloRusk) - [website](https://hellorusk.net)

とするので良いでしょうか。

**Comment by taishi-i** [comment]
@HelloRusk もちろん大丈夫ですよ！よろしくお願いします🙏
