### ISSUE TITLE
Request for inclusion: yomigana-ebook - a faster tool for adding kanji readings to ebooks

### ISSUE THREAD

**Issue by rabbit19981023** [taishi-i/awesome-japanese-nlp-resources#11]
Hello,

I would like to bring your attention to a tool called [yomigana-ebook](https://github.com/rabbit19981023/yomigana-ebook) that I have developed. This tool efficiently adds readings for kanji in eBooks and boasts a performance that is 4x faster when compared to [furigana4epub](https://github.com/Mumumu4/furigana4epub), as observed on my computer. The implementation of both tools leverages the multiprocessing library.

I kindly request considering the inclusion of this tool in the list.

Thank you for your time and consideration.

p.s. the title and content is generated from chatgpt because of my poor english.

**Comment by taishi-i** [comment]
Hi @rabbit19981023! Thank you for your proposal! I would like to add it to this list. I will include it in the next update and make it available in multiple languages. Please wait a little while!

**Comment by taishi-i** [comment]
Hi @rabbit19981023! Based on the information provided, I have published the repository. I have also translated it into multiple languages.
 
https://github.com/taishi-i/awesome-japanese-nlp-resources/blob/6bca8ee8550a82b147abddd7263d283ea426c239/README.md?plain=1#L26

https://github.com/taishi-i/awesome-japanese-nlp-resources/blob/6bca8ee8550a82b147abddd7263d283ea426c239/README.md?plain=1#L429

If you have a website you would like to promote and would like to be added as a contributor, please edit the following line and send a pull request. Thank you in advance.

https://github.com/taishi-i/awesome-japanese-nlp-resources/blob/6bca8ee8550a82b147abddd7263d283ea426c239/README.md?plain=1#L30

**Comment by rabbit19981023** [comment]
Wow, thank you for the fast update!

No, I have no personal website, it's ok.

And I found another repo which does the same thing: [furiganalyse](https://github.com/itsupera/furiganalyse), it seems faster (about 20%) than my tool if he properly use multiprocess (tested on my computer).

**Comment by taishi-i** [comment]
Thank you for sharing the new information. I will update this information in the next update.
The information here has been updated and this issue is closed. I'm looking forward to receiving more information from you in the future. Thank you!
