### ISSUE TITLE
Punctuation tools

### ISSUE THREAD

**Issue by dgoryeo** [taishi-i/awesome-japanese-nlp-resources#13]
Hi @taishi-i , thank you so much for this helpful list of resources. 
Would you any tool that can perform punctuation in Japanese text? 
Ideally a machine learning model that predicts where a puctuation is needed in a text.

Thanks

**Comment by kaisugi** [comment]
I don't come up with any tools but I'm sure GPT-4 can solve such tasks easily 
(the example text below is taken from [today's news](https://www3.nhk.or.jp/shutoken-news/20231015/1000098193.html), which means the model doesn't just memorize it)

<img width="811" alt="スクリーンショット 2023-10-15 15 45 23" src="https://github.com/taishi-i/awesome-japanese-nlp-resources/assets/36184621/13919eb1-44d7-450e-9637-2995d8786ac3">

**Comment by dgoryeo** [comment]
Great thinking @kaisugi . I'll look into it. Thanks!

**Comment by taishi-i** [comment]
Hi @dgoryeo, thank you for your comment. I don't know of a tool specifically designed to add punctuation to Japanese text. However, there are three ideas to achieve this:

# 1. BudouX or bunkai

The first idea is to use tools like [BudouX](https://github.com/google/budoux) or [bunkai](https://github.com/megagonlabs/bunkai). While these tools are not specifically for punctuation detection, they may perform similar processing and could be expected to add punctuation.

Here is an example of BudouX processing.

```bash
pip install budoux
```

```python
import budoux
parser = budoux.load_default_japanese_parser()
print(parser.parse('今日は天気です。'))
# ['今日は', '天気です。']
```

It also has a way to create custom models to segment a sentence. https://github.com/google/budoux#building-a-custom-model

# 2. OpenAI API (or ChatGPT in your browser)

The second idea is to use the OpenAI API or ChatGPT. As per his description, I think that ChatGPT could be used to solve this problem. Thank you, @kaisugi!

# 3. Train a segmentation model

The third idea is to train your own machine learning model. This involves training a model to predict the locations of punctuation marks in the intended domain. Since you can obtain punctuation marks without annotations, you can create a punctuation adding tool by training the model on this pattern.

```
今日は、晴れです。
```
I think the process can be achieved by converting the above statement to the following form and training a machine learning model.

```
明 0
日 0
は 1
晴 0
れ 0
で 0
す 0
天 0
気 0
で 0
す 2
<EOS> 0
```


This model is easy to train, I'll give it a try, give me 24 hours. I will contact you again.

**Comment by dgoryeo** [comment]
Thank you so much @taishi-i ! I will look into both option 1 and 2. The 3rd option is too ambitious for me, I won't be able to achieve that. Thanks again.

**Comment by taishi-i** [comment]
Hi @dgoryeo, I have created a Japanese punctuation model. If you are interested, please try it out.

First, please install the following library.

```bash
pip install nagisa
```

After installing the library, please download [the model files (model_to_add_punctuation.zip)](https://github.com/taishi-i/awesome-japanese-nlp-resources/files/12918225/model_to_add_punctuation.zip) uploaded to this page, unzip zip file and run the following code.


```python
import nagisa

base_name = "model_to_add_punctuation"

tagger = nagisa.Tagger(
    vocabs=f"{base_name}.vocabs",
    params=f"{base_name}.params",
    hp=f"{base_name}.hp",
)

text = "突然ですがこれは日本語句読点付与プログラムです試してみてください"

tokens = tagger.tagging(text)

words = tokens.words
tags = tokens.postags

outputs = []
for word, tag in zip(words, tags):
    outputs.append(word)
    if tag == "1":
        outputs.append("、")
    elif tag == "2":
        outputs.append("。")

# 突然ですがこれは日本語句読点付与プログラムです試してみてください
print(text)

# 突然ですが、これは日本語句読点付与プログラムです。試してみてください。
print("".join(outputs))
```

Here are the scripts for creating the training data and the training script. Please use your favorite corpus.

<details>
<summary>create_datasets.py</summary>

```python
import random

import nagisa


def annotate(words):
    punctuation_marks = ["、", "。"]
    punctuation_marks2label = {
        punctuation_marks[0]: "1",
        punctuation_marks[1]: "2",
    }

    inputs = []
    tags = []

    remove_punctuation_mark = False

    num_words = len(words)
    for i in range(num_words - 1):
        current_word = words[i]
        next_word = words[i + 1]

        if current_word in punctuation_marks:
            if remove_punctuation_mark is True:
                None
            else:
                inputs.append(current_word)
                tags.append("0")

        else:
            if next_word in punctuation_marks:
                random_int = random.randint(0, 1)
                if random_int == 0:
                    remove_punctuation_mark = True
                    inputs.append(current_word)
                    tag = punctuation_marks2label[next_word]
                    tags.append(tag)
                else:
                    inputs.append(current_word)
                    tags.append("0")
                    remove_punctuation_mark = False

            else:
                inputs.append(current_word)
                tags.append("0")

    last_word = next_word
    if last_word in punctuation_marks and remove_punctuation_mark is False:
        inputs.append(last_word)
        tags.append("0")

    assert len(inputs) == len(tags)
    return inputs, tags


def write_file(data, file_name):
    with open(file_name, "w") as f:
        for inputs_and_tags in data:
            inputs, tags = inputs_and_tags
            for word, tag in zip(inputs, tags):
                f.write(f"{word}\t{tag}\n")
            f.write("EOS\n")


def main():
    random.seed(1234)

    max_data = 125000
    file_name = "corpus_01.txt"

    data = []
    with open(file_name, "r") as f:
        for line in f:
            line = line.strip()
            if len(line.strip()) > 0:
                words = nagisa.wakati(line)
                inputs, tags = annotate(words)

                if len(inputs) > 0 and len(tags) > 0:
                    data.append([inputs, tags])
                if len(data) > max_data:
                    break

    random.shuffle(data)

    base_name = "model_to_add_punctuation"
    train_file = f"{base_name}.train"
    dev_file = f"{base_name}.dev"
    test_file = f"{base_name}.test"

    num_train = int(len(data) * 0.8)
    num_dev = int(len(data) * 0.1)

    train_data = data[:num_train]
    dev_data = data[num_train : num_train + num_dev]
    test_data = data[num_train + num_dev :]

    write_file(train_data, train_file)
    write_file(dev_data, dev_file)
    write_file(test_data, test_file)

    print(
        f"train: {len(train_data)}, dev: {len(dev_data)}, test:"
        f" {len(test_data)}"
    )


if __name__ == "__main__":
    main()
```

</details>

<details>
<summary>train.py</summary>

```python
import nagisa


nagisa.fit(
    train_file="model_to_add_punctuation.train",
    dev_file="model_to_add_punctuation.dev",
    test_file="model_to_add_punctuation.test",
    model_name="model_to_add_punctuation",
)
```

</details>

**Comment by dgoryeo** [comment]
Wow, thanks @taishi-i . I will definitely check it out and will le you know. It will probably be towars the end of he week. Thanks again!

**Comment by taishi-i** [comment]
OK! If you have any other comments, please feel free to send them. Good luck!

**Comment by dgoryeo** [comment]
Quick follow up note: I was able to install nagisa and run the script right away. All went well with flying colours. I will test it with my usecase later this week. I'll let you know. Much appreciated!

**Comment by taishi-i** [comment]
When I used a model downloaded from GitHub for verification, a permission error occurred, so I re-uploaded the model that resolved the issue. If you get a similar error, please use this [the model files (model_to_add_punctuation.zip)](https://github.com/taishi-i/awesome-japanese-nlp-resources/files/12918225/model_to_add_punctuation.zip).

**Comment by dgoryeo** [comment]
Hi @taishi-i , I took the liberty to share your approach in this thread in OpenAI Whisper commnity [stable-ts](https://github.com/jianfch/stable-ts/discussions/224#discussioncomment-7303156). Hope you don't mind.

**Comment by taishi-i** [comment]
Hi @dgoryeo! It's okay, no problem. I think you should choose the most optimal method to solve your problem.
If this issue is resolved, please close this issue. If you have any further comments, I am always happy to hear from you. Thank you.
